ModuleClass: org.labkey.sivstudies.SivStudiesModule
Label: SIV Studies
Description: A module designed to manage data from SIV and related studies.
License: Apache 2.0
LicenseURL: http://www.apache.org/licenses/LICENSE-2.0
ManageVersion: false
SupportedDatabases: mssql, pgsql
