# Designed to keep develop branch as a perfect copy of LabKey fork
on:
  schedule:
    - cron:  "5 */3 * * *"
jobs:
  sync-release-branches:
    # See: https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
    # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
    if: github.repository == 'BimberLabInternal/BimberLabKeyModules'
    runs-on: ubuntu-latest
    steps:
      - name: "Sync Release Branches"
        uses: bimberlabinternal/DevOps/githubActions/branch-create@master
        with:
          source_repo: "labkey/BimberLabKeyModules"
          source_branch_prefix: "release"
          destination_repo: "BimberLabInternal/BimberLabKeyModules"
          destination_branch_prefix: "discvr-"
          # NOTE: permissions are limited on the default secrets.GITHUB_TOKEN, including updating workflows, so use a personal access token
          github_token: ${{ secrets.PAT }}
  sync-develop:
    if: github.repository == 'BimberLabInternal/BimberLabKeyModules'
    runs-on: ubuntu-latest
    steps:
      - name: "Sync Develop Branch"
        uses: bimberlabinternal/DevOps/githubActions/git-sync@master
        with:
          source_repo: "labkey/BimberLabKeyModules"
          source_branch: "develop"
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
